# src/weaver.py
import os
import re
import yaml
from pathlib import Path
from src.contracts import DIRS, ThreadManifest, TreeNode, calculate_hash

def clean_filename(title):
    keep = (" ", ".", "_", "-")
    clean = "".join(c for c in title if c.isalnum() or c in keep).strip()
    return clean.replace(" ", "_")

def get_unique_filename(directory, base_name):
    filename = f"{clean_filename(base_name)}.md"
    path = directory / filename
    if not path.exists():
        return path
    counter = 2
    while True:
        filename = f"{clean_filename(base_name)}_v{counter}.md"
        path = directory / filename
        if not path.exists():
            return path
        counter += 1

def create_atom(title, content, metadata=None):
    """
    Creates an atomic note with YAML frontmatter.
    Calculates hash to prevent duplicates if similar content exists.
    """
    path = get_unique_filename(DIRS["ATOMS"], title)
    
    # Calculate hash for robustness
    content_hash = calculate_hash(content)
    
    if metadata:
        metadata['content_hash'] = content_hash
    
    fm = "---\n"
    if metadata:
        fm += yaml.dump(metadata, sort_keys=False)
    fm += "---\n\n"
    
    content = content.strip()
    
    with open(path, "w", encoding="utf-8") as f:
        f.write(fm + content)
        
    return path

def update_atom_content(atom_filename: str, appended_text: str):
    """
    Stitches new content into an existing atom.
    Used when the Librarian decides to 'Merge' rather than 'Split'.
    """
    path = DIRS["ATOMS"] / atom_filename
    if not path.exists():
        return False
        
    with open(path, "r", encoding="utf-8") as f:
        raw = f.read()
        
    # Simple append logic. 
    # Improvement: In future, use LLM to smooth the transition.
    new_content = raw.strip() + "\n\n" + appended_text.strip()
    
    with open(path, "w", encoding="utf-8") as f:
        f.write(new_content)
    
    return True

def render_node(node: TreeNode) -> str:
    """
    Recursively renders a tree node into Markdown.
    Supports SEAMLESS rendering to fix the 'Broken Flow' issue.
    """
    markdown = ""
    
    # Load Atom Content
    atom_path = DIRS["ATOMS"] / node.atom_id
    if atom_path.exists():
        with open(atom_path, "r", encoding="utf-8") as f:
            raw = f.read()
            # Strip frontmatter
            parts = raw.split("---", 2)
            body = parts[2].strip() if len(parts) >= 3 else raw.strip()
    else:
        body = "*Atom file missing*"

    # === LOGIC UPGRADE: Reading Flow ===
    # If style is seamless, WE DO NOT PRINT THE HEADER.
    # This allows Paragraph A to flow into Paragraph B.
    if node.render_style == "seamless":
        header_block = ""
    else:
        header_block = f"{'#' * node.level} {node.title}\n\n"
    
    # 1. Start Marker (Required for syncing edits back)
    markdown += f"\n<!-- source: Atoms/{node.atom_id} -->\n"
    
    # 2. Visible Content
    markdown += f"{header_block}{body}\n"
    
    # 3. End Marker REMOVED as per user request. 
    # The parser will assume content ends when the next <!-- source: ... --> begins.

    # Render Children
    for child in node.children:
        markdown += render_node(child)
        
    return markdown

def rebuild_thread_markdown(manifest: ThreadManifest):
    """
    Completely regenerates the Thread file from the Manifest.
    """
    file_path = DIRS["THREADS"] / f"{manifest.thread_id}.md"
    
    content = f"# {manifest.title}\n\n"
    content += "*Generated by Obsidian Brain v3.0*\n"
    
    for node in manifest.nodes:
        content += render_node(node)
        
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
        
    return file_path

def append_to_manuscript(thread_name, atom_path, category="thread", project_meta=None):
    """
    Legacy wrapper. Now intelligently adds to Manifest.
    """
    if category == "project" and not thread_name.startswith("P. "):
        thread_id = f"P. {thread_name}"
    elif not thread_name.startswith(("T. ", "P. ")):
        thread_id = f"T. {thread_name}"
    else:
        thread_id = thread_name

    manifest = ThreadManifest.load(thread_id)
    atom_filename = Path(atom_path).name
    title = Path(atom_path).stem.replace("_", " ")

    # Legacy append defaults to Standard style
    manifest.add_node_flat(atom_id=atom_filename, title=title, render_style="standard")
    
    manifest.save()
    rebuild_thread_markdown(manifest)